### ISSUE TITLE
Peaks (360°) in Error Angle Scope

### ISSUE THREAD

**Issue by BadHermano** [nauaneed/CompleteAttDetSim#1]
i have done a longterm simulation 24*3600 and watched the scope of the error angles. Sometimes there appears high peaks of an error of 360°. Any Idea where this comes from ?

**Comment by nauaneed** [comment]
Well, 360°=0°

Since the errors being introduced are normally distributed, it is possible that we may get a very large error momentarily. We can actually expect a peak of 180°. I will make a modification to avoid this confusion. 

Note that these are errors in attitude determination when we are only using a classic 2 vector pair attitude determination algorithm. In other words, this is just the error in how the satellite perceives its attitude.

This error does try to misguide the reaction control system but it will not actually follow these high rate of fluctuations. Also, by introducing gyro inputs and some filtering to go with this attitude determination algorithm we will have a much smoother attitude estimate. (Planned next!).
